# -*- coding: utf-8 -*-
"""CurbRampModel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zm3-c2UtvKPkNRxoATIj0NzbZKnIo4Z3
"""

!pip install evaluate scikit-learn matplotlib
import torch
import evaluate
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
from torchvision.transforms import RandomHorizontalFlip
from google.colab import userdata
from huggingface_hub import login
from datasets import load_dataset, interleave_datasets
from transformers import (
    AutoImageProcessor,
    AutoModelForImageClassification,
    TrainingArguments,
    Trainer,
    DefaultDataCollator
)

login(token=userdata.get('HF_TOKEN'))

def train_model():
    training_dataset = load_dataset("projectsidewalk/sidewalk-validator-ai-dataset-curbramp", split="train", streaming=True)
    validation_dataset = load_dataset("projectsidewalk/sidewalk-validator-ai-dataset-curbramp", split="validation", streaming=True)
    testing_dataset = load_dataset("projectsidewalk/sidewalk-validator-ai-dataset-curbramp", split="test", streaming=True)

    training0 = training_dataset.filter(lambda x: x["label"] == 0).take(506)
    training1 = training_dataset.filter(lambda x: x["label"] == 1).take(506)
    validation0 = validation_dataset.filter(lambda x: x["label"] == 0).take(109)
    validation1 = validation_dataset.filter(lambda x: x["label"] == 1).take(109)
    testing0 = testing_dataset.filter(lambda x: x["label"] == 0).take(115)
    testing1 = testing_dataset.filter(lambda x: x["label"] == 1).take(115)

    training = interleave_datasets([training0, training1], probabilities=[0.5, 0.5], seed=42)
    validation = interleave_datasets([validation0, validation1], probabilities=[0.5, 0.5], seed=42)
    testing = interleave_datasets([testing0, testing1], probabilities=[0.5, 0.5], seed=42)

    checkpoint = "facebook/convnext-tiny-224"

    processor = AutoImageProcessor.from_pretrained(checkpoint)
    flip = RandomHorizontalFlip(p=0.5)

    def transform(batch):
        images = [flip(x.convert("RGB")) for x in batch["image"]]
        inputs = processor(images, return_tensors="pt")
        inputs["labels"] = torch.tensor(batch["label"])
        return inputs

    training_prepared = training.map(transform, batched=True, remove_columns=['image'])
    validation_prepared = validation.map(transform, batched=True, remove_columns=['image'])
    testing_prepared = testing.map(transform, batched=True, remove_columns=['image'])

    accuracy_metric = evaluate.load("accuracy")

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        predictions = np.argmax(logits, axis=-1)
        return accuracy_metric.compute(predictions=predictions, references=labels)

    training_args = TrainingArguments(
        output_dir="./optimized_curb_model",
        max_steps=600,
        learning_rate=3e-5,
        lr_scheduler_type="cosine",
        warmup_steps=50,
        per_device_train_batch_size=8,
        fp16=True,
        logging_steps=10,
        eval_strategy="steps",
        eval_steps=50,
        save_total_limit=1,
        load_best_model_at_end=True,
        metric_for_best_model="accuracy",
        label_smoothing_factor=0.1,
        remove_unused_columns=True,
        report_to="none"
    )

    model = AutoModelForImageClassification.from_pretrained(
        checkpoint, num_labels=2, ignore_mismatched_sizes=True
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=training_prepared,
        data_collator=DefaultDataCollator(),
        eval_dataset=validation_prepared,
        compute_metrics=compute_metrics
    )

    print("Starting training...")
    trainer.train()

    #CONFUSION MATRIX GENERATION#
    print("\nGenerating Confusion Matrix on Test Set...")
    # Get predictions for the test set
    outputs = trainer.predict(testing_prepared)
    y_true = outputs.label_ids
    preds = outputs.predictions
    probs = np.exp(preds)/np.exp(preds).sum(axis=1, keepdims=True)
    prob_curb = probs[:,0]
    threshold = 0.91
    y_pred = (prob_curb <= threshold).astype(int)

    # Calculate Matrix
    cm = confusion_matrix(y_true, y_pred)

    # Plotting
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Curb Ramp', 'No Curb Ramp'],
                yticklabels=['Curb Ramp', 'No Curb Ramp'])
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.title('Confusion Matrix: Curb Ramp Detection')
    plt.show()

    print("\nDetailed Classification Report:")
    print(classification_report(y_true, y_pred, target_names=['Curb Ramp', 'No Curb Ramp']))

    return model, processor

if __name__ == "__main__":
    model, processor = train_model()